### ISSUE TITLE
貌似utils.js里面的post函数有bug

### ISSUE THREAD

**Issue by yqs112358** [HaleShaw/uTools-Translate#4]
如题
<img width="551" alt="image" src="https://github.com/HaleShaw/uTools-Translate/assets/37969157/e096b23f-c148-42bb-9fa8-693f5e62ec53">
Fetch API在返回除200之外的其他状态时，不会抛出异常，而是仍然走then逻辑，于是碰到resolve(res.json())发生json解析失败，导致错误信息无法正常显示。

可作如下修改
<img width="538" alt="image" src="https://github.com/HaleShaw/uTools-Translate/assets/37969157/af094b1e-786f-4380-8dc5-23014b0a12eb">
并在所有用到post的地方都套上try catch保证捕获

**Comment by HaleShaw** [comment]
其实目前也就DeepL API会用到原生Http状态码。已于v3.2.4修复。
