### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by listenkeep** [HaleShaw/uTools-Translate#6]
1. 源语言与目标语言的选择逻辑较简单, 容易误判, 目前是只要有中文字符就会中翻英. 例子: happy everyday, high 起来
2. 不展示源语言与目标语言, 缺乏展示与手动变更功能
3. 长本文列表展示不全, 似乎与快速翻译的原则不符, 建议可以加配置项: 是否自动分行展开全文, 并且默认展开

**Comment by HaleShaw** [comment]
> 1. 源语言与目标语言的选择逻辑较简单, 容易误判, 目前是只要有中文字符就会中翻英. 例子: happy everyday, high 起来
> 2. 不展示源语言与目标语言, 缺乏展示与手动变更功能
> 3. 长本文列表展示不全, 似乎与快速翻译的原则不符, 建议可以加配置项: 是否自动分行展开全文, 并且默认展开

1. 关于1、2，在翻译界面确实不会展示翻译方向（如：英->中）。在设置界面，有提供相关选项来设置，部分API是支持设置翻译方向的。
2. 在v4.1.0版本中已经实现自适应显示过长翻译结果。Enjoy your self after the approval!
