### ISSUE TITLE
请问能多行翻译吗？

### ISSUE THREAD

**Issue by Cope9560** [HaleShaw/uTools-Translate#9]
默认是单行的，没找到地方修改

**Comment by HaleShaw** [comment]
> 默认是单行的，没找到地方修改

单行或多行，是由翻译的源文本决定的。如果源文本短，那么一行就能显示完翻译结果，如果源文本长，翻译结果一行显示不完，就会自动多行显示。

---
如果你问的指多行的翻译结果，那是不同的API引擎翻译结果不同。有些翻译引擎的结果就只有一个结果，有些翻译引擎会有多行，包含如变形、句子等结果。
可以尝试不同的API引擎看看效果。
输入`翻译设置`，`设置`，`setting`，`ts`等关键字进入设置页面。

---
点击插件，可查看插件拥有的各种关键字。

**Comment by Cope9560** [comment]
但是翻译窗口无法粘贴多行内容进去，会变成单行

**Comment by HaleShaw** [comment]
> 但是翻译窗口无法粘贴多行内容进去，会变成单行

直接输入框中是无法输入换行符的，但是比如在记事本中有多行内容（即便包含换行符），也可以全部一起粘贴进翻译输入框的。

**Comment by Cope9560** [comment]
![PixPin_2024-07-24_14-20-30](https://github.com/user-attachments/assets/a8bceda5-9417-4711-9c60-7fb794b27184)

**Comment by Cope9560** [comment]
> > 但是翻译窗口无法粘贴多行内容进去，会变成单行
> 
> 直接输入框中是无法输入换行符的，但是比如在记事本中有多行内容（即便包含换行符），也可以全部一起粘贴进翻译输入框的。

记事本中复制进去也不行

**Comment by HaleShaw** [comment]
> > > 但是翻译窗口无法粘贴多行内容进去，会变成单行
> > 
> > 
> > 直接输入框中是无法输入换行符的，但是比如在记事本中有多行内容（即便包含换行符），也可以全部一起粘贴进翻译输入框的。
> 
> 记事本中复制进去也不行

你这粘贴进去的不是有9行内容吗，9行内容全部都翻译出来了呀~
只是翻译结果它不会再像你的源文本那样分成9行而已。因为它是一次性翻译出来的，不是分成9行单独去翻译的。

**Comment by Cope9560** [comment]
> > > > 但是翻译窗口无法粘贴多行内容进去，会变成单行
> > > 
> > > 
> > > 直接输入框中是无法输入换行符的，但是比如在记事本中有多行内容（即便包含换行符），也可以全部一起粘贴进翻译输入框的。
> > 
> > 
> > 记事本中复制进去也不行
> 
> 你这粘贴进去的不是有9行内容吗，9行内容全部都翻译出来了呀~ 只是翻译结果它不会再像你的源文本那样分成9行而已。因为它是一次性翻译出来的，不是分成9行单独去翻译的。

能否让翻译结果保持原格式呢

**Comment by HaleShaw** [comment]
> > > > > 但是翻译窗口无法粘贴多行内容进去，会变成单行
> > > > 
> > > > 
> > > > 直接输入框中是无法输入换行符的，但是比如在记事本中有多行内容（即便包含换行符），也可以全部一起粘贴进翻译输入框的。
> > > 
> > > 
> > > 记事本中复制进去也不行
> > 
> > 
> > 你这粘贴进去的不是有9行内容吗，9行内容全部都翻译出来了呀~ 只是翻译结果它不会再像你的源文本那样分成9行而已。因为它是一次性翻译出来的，不是分成9行单独去翻译的。
> 
> 能否让翻译结果保持原格式呢

这个插件的初衷是轻量级翻译，快速显示翻译结果，所以是列表形式的翻译结果。
暂时不太会考虑做这个优化。因为这相当于主要用于复制粘贴多段落文本翻译的场景，对于使用这个插件的人来说频率不高，且适配比较麻烦。
就算要适配，也可能只能是针对某一个API去做特殊的处理，因为有些API一个词会出来多个结果。
![全局快捷键](https://github.com/user-attachments/assets/549bc905-344f-4856-947a-e99468a7ccaa)
![快速翻译](https://github.com/user-attachments/assets/046e2466-195a-4216-92ee-a3da1923f812)
